# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d7326540c9876bf384b41950d396d608"
name = "beneficial-negotiation-app"
handle = "beneficial-negotiation-app-12"
application_url = "https://camel-queensland-natural-protest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "retrytest.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://camel-queensland-natural-protest.trycloudflare.com/auth/callback",
  "https://camel-queensland-natural-protest.trycloudflare.com/auth/shopify/callback",
  "https://camel-queensland-natural-protest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
